name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a Bug Report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Please tell us about the bug as detailed as possible.
        Feel free to also add Media and CrashLogs!
    validations:
      required: true
  - type: dropdown
    id: lua-node-version
    attributes:
      label: Lua Node Editor Version
      description: Which version of the Lua Node Editor are you using?
      options:
        - "V1.0"
    validations:
      required: true
# For if you have multiple Bug types
#  - type: checkboxes
#   id: related
#   attributes:
#     label: Type of Bug
#     description: What type of bug is this?
#     options:
#       - label: bugtype 1
#       - label: bugtype 2
#       - label: bugtype 3
  - type: textarea
    id: more-information
    attributes:
      label: More information
      description: Is there anything else relevant that you want/need to share.
